# Generated by Django 4.0.1 on 2022-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenbergID', models.IntegerField(default='-1')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('gutenbergID',),
            },
        ),
    ]
