# Generated by Django 4.0.1 on 2022-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
