# Generated by Django 4.0.1 on 2022-01-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_id_alter_book_gutenbergid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
