# Generated by Django 4.0.1 on 2022-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
