# Generated by Django 4.0.1 on 2022-01-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
        migrations.CreateModel(
            name='IndexWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('idBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('idWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.words')),
            ],
            options={
                'ordering': ('idBook',),
            },
        ),
    ]
