# Generated by Django 4.0.1 on 2022-01-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_words_indexwords'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexwords',
            unique_together={('idWord', 'idBook')},
        ),
    ]
