# Generated by Django 4.0.1 on 2022-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_indexwords_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
