# Generated by Django 4.0.1 on 2022-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='word',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
