# Generated by Django 4.0.1 on 2022-01-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_blacklist_id_alter_blacklist_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blacklist',
            new_name='BlacklistWords',
        ),
    ]
