# Generated by Django 4.0.1 on 2022-02-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_jackaldistance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JackalDistance',
            new_name='JaccardDistance',
        ),
    ]
