# Generated by Django 4.0.1 on 2022-02-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_rename_jackaldistance_jaccarddistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('idBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'ordering': ('idBook',),
                'unique_together': {('idBook',)},
            },
        ),
    ]
